### ISSUE TITLE
Build successfully but getting the r interpreter not found

### ISSUE THREAD

**Issue by Nirosan** [datalayer/zeppelin-datalayer#10]
Able to build the rscala-z branch successfully. When I run the examples provided in the R-notebook the following error is thrown.

`ERROR [2016-04-11 11:46:58,074] ({qtp1423077782-31} NotebookServer.java[runParagraph]:989) - Exception from run
org.apache.zeppelin.interpreter.InterpreterException: r interpreter not found
        at org.apache.zeppelin.notebook.NoteInterpreterLoader.get(NoteInterpreterLoader.java:186)
        at org.apache.zeppelin.notebook.Note.run(Note.java:375)
        at org.apache.zeppelin.socket.NotebookServer.runParagraph(NotebookServer.java:987)
        at org.apache.zeppelin.socket.NotebookServer.onMessage(NotebookServer.java:162)
        at org.apache.zeppelin.socket.NotebookSocket.onMessage(NotebookSocket.java:56)
        at org.eclipse.jetty.websocket.WebSocketConnectionRFC6455$WSFrameHandler.onFrame(WebSocketConnectionRFC6455.java:835)
        at org.eclipse.jetty.websocket.WebSocketParserRFC6455.parseNext(WebSocketParserRFC6455.java:349)
        at org.eclipse.jetty.websocket.WebSocketConnectionRFC6455.handle(WebSocketConnectionRFC6455.java:225)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:667)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:745)`

**Comment by felansu** [comment]
+1 same error

**Comment by echarles** [comment]
The R feature is now merged into the Apache zeppelin source code. Best to use it from there (in other words, it won't be fixed here).

**Comment by felansu** [comment]
@echarles thanks
